language: python

python:
  - "3.7"


install:
   - pip install -r requirements.txt

before_script:
  - python manage.py migrate

after_script:
  - coveralls

script:
  # Run Black formatter
  - black --check .

  # Run Flake8 linter
  - flake8 .
  # Run Django tests
  - coverage run manage.py test
