language: python

python:
  - "3.7"


install:
   - pip install -r requirements.txt

before_script:
  - python manage.py migrate

after_script:
  - coveralls

script:
  # Run Black formatter
  - black --check .

  # Run Flake8 linter
  - flake8 --extend-ignore E501,F401,F811
  # Run Django tests
  - coverage run manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $ACCESS_KEY
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-483748588056"
  bucket_path: "django-tutorial/"
  on:
    repo: ls4934/swe1-app
    branch: master